os: linux
language: python

python:
  - 3.9
  - 3.8
  - 3.7

env:
  - DJANGO==3.1 DB==sqlite
  
install:
  - pip install -r PetBook/requirements.txt
  - pip install -q Django=$DJANGO
  - python setup.py -q install
