"""New files

Revision ID: 077fbfa54c6c
Revises: 877e9996b751
Create Date: 2021-02-28 12:40:31.314566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077fbfa54c6c'
down_revision = '877e9996b751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('puppies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('owners')
    op.drop_table('pets')
    # ### end Alembic commands ###
